// components/ui/Contact/Contact.jsx
import GradientWrapper from "../../GradientWrapper"
import Button from "../Button";

const Contact = () => {
    return (
        <GradientWrapper id="contact" className="overflow-hidden dark:overflow-visible dark:my-0 sm:my-16">
            <div className="custom-screen gap-12 justify-between md:flex">
                <div className='relative max-w-2xl text-gray-300'>
                    <h2 className='text-gray-50 text-3xl font-semibold sm:text-4xl'>
                        Contact Information
                    </h2>
                    <p className='mt-3 max-w-xl'>
                        Feel free to explore my social channels for additional insights or if you're interested in
                        potential collaborations: <br/><br/>
                        Email ➣ contact@jacob-j.com <br/>
                        GitHub ➣ <br/>
                        LinkedIn ➣
                    </p>
                </div>
                <div className="mt-12 bg-white dark:bg-gray-900/50 rounded-xl shadow-lg md:mt-0">
                    <div className="h-full p-6 space-y-3">
                        <div className="flex flex-wrap items-center justify-between gap-3">
                            <span className="text-2xl text-gray-800 dark:text-gray-50 font-semibold">
                                Contact Me
                            </span>
                            <div className="text-2xl text-gray-800 dark:text-gray-50 font-semibold">
                                !!!
                            </div>

                        </div>
                        <p className="max-w-sm text-gray-600 dark:text-gray-300">
                            You are welcome to reach out to me by email at:
                            contact@jacob-j.com
                        </p>
                        <Button className="block w-full text-white bg-blue-600 dark:bg-sky-500 hover:bg-blue-500 dark:hover:bg-sky-600 ring-offset-2 ring-blue-600 dark:ring-sky-500 focus:ring shadow">
                            Coming Soon
                        </Button>
                    </div>
                </div>
            </div>
        </GradientWrapper>
    )
}

export default Contact

// src/routes/contact/+page.svelte
<script>
    import AmbientColor from "$lib/components/ui/AmbientColor.svelte";
    import SocialButton from "$lib/components/SocialButton.svelte";
</script>

<main class="text-text p-6 fade-in min-h-screen flex items-center justify-center">
    <AmbientColor/>

    <div class="flex flex-col md:flex-row items-center justify-center gap-16 w-full max-w-6xl transform -translate-y-24">
        <div class="flex flex-col justify-center space-y-12 w-full md:w-1/2 text-center mx-auto">
            <div class="space-y-4">
                <h2 class="text-3xl md:text-4xl font-bold mb-4 text-accent z-20">
                    Contact
                </h2>
                <div class="space-y-12 max-w-md text-text z-20 mx-auto">
                    <p>
                        Feel free to reach out to me through any of the channels below.
                    </p>
                </div>
            </div>

            <div class="flex flex-col md:flex-row items-center justify-center space-y-6 md:space-y-0 md:space-x-12 mx-auto">
                <SocialButton
                        href="mailto:contact@jacob-j.com?subject=Hello Jacob&body=Hi Jacob,%0A%0A"
                        text="contact@jacob-j.com"
                        title="Email"/>

                <SocialButton
                        href="https://www.linkedin.com/in/jacob-j-in/"
                        text="Jacob Jørgensen"
                        title="LinkedIn"/>
            </div>

            <div class="mt-12 text-sm text-text z-20">
                <p>
                    You can also explore more of my work on
                    <a class="text-accent" href="https://github.com/zelvios">GitHub</a>:
                    <a class="font-semibold underline hover:text-accent" href="https://github.com/zelvios">zelvios</a>.
                </p>
            </div>
        </div>
    </div>
</main>

<style>
    .fade-in {
        animation: fadeIn 1s ease-out;
    }

    @keyframes fadeIn {
        0% {
            opacity: 0;
            transform: translateY(20px);
        }
        100% {
            opacity: 1;
            transform: translateY(0);
        }
    }
</style>
