// src/components/hero/Hero.jsx
import React, { useEffect, useState } from "react";
import { motion } from "framer-motion";
import { FiArrowRight } from "react-icons/fi";
import { twMerge } from "tailwind-merge";

// Main Component
export const DarkGridHero = () => {
    return (
        <section className="section-wrapper" id="hero">
            <div className="absolute top-0 left-0 right-0 overflow-hidden bg-zinc-950 flex items-center justify-center" style={{ height: '900px' }}>
                <Content />
                <Beams />
                <GradientGrid />
            </div>
            <div className="pt-[900px]"></div>
        </section>
    );
};

// Content
const Content = () => {
    return (
        <div className="relative z-20 mx-auto flex max-w-6xl flex-col items-center justify-center px-4 py-24 md:px-8 md:py-36">
            <motion.div
                initial={{ y: 25, opacity: 0 }}
                animate={{ y: 0, opacity: 1 }}
                transition={{ duration: 1.25, ease: "easeInOut" }}
                className="relative"
            >
                <GlowingChip>Site is still WIP 🎉</GlowingChip>
            </motion.div>
            <motion.h1
                initial={{ y: 25, opacity: 0 }}
                animate={{ y: 0, opacity: 1 }}
                transition={{ duration: 1.25, delay: 0.25, ease: "easeInOut" }}
                className="mb-3 text-center text-3xl font-bold leading-tight text-zinc-50 sm:text-4xl sm:leading-tight md:text-5xl md:leading-tight lg:text-7xl lg:leading-tight"
            >
                Hi, I am Jacob
            </motion.h1>
            <motion.p
                initial={{ y: 25, opacity: 0 }}
                animate={{ y: 0, opacity: 1 }}
                transition={{ duration: 1.25, delay: 0.5, ease: "easeInOut" }}
                className="mb-9 max-w-2xl text-center text-base leading-relaxed text-zinc-400 sm:text-lg md:text-lg md:leading-relaxed"
            >
                Welcome to my Portfolio
            </motion.p>
            <motion.div
                initial={{ y: 25, opacity: 0 }}
                animate={{ y: 0, opacity: 1 }}
                transition={{ duration: 1.25, delay: 0.75, ease: "easeInOut" }}
                className="flex flex-col items-center gap-6 sm:flex-row"
            >
                <SplashButton
                    className="flex items-center gap-2"
                    onClick={(e) => handleLinkClick(e, "contact")}
                >
                    Contact Me
                    <FiArrowRight />
                </SplashButton>
                <DrawOutlineButton className="rounded-md px-4 py-2 text-zinc-100"
                                   onClick={(e) => handleLinkClick(e, "projects")}>
                    Projects
                </DrawOutlineButton>
            </motion.div>
        </div>
    );
};

// Buttons
const GlowingChip = ({ children }) => {
    return (
        <span className="relative z-10 mb-4 inline-block rounded-full border border-zinc-700 bg-zinc-900/20 px-3 py-1.5 text-xs text-zinc-50 md:mb-0">
            {children}
            <span className="absolute bottom-0 left-3 right-3 h-[1px] bg-gradient-to-r from-zinc-500/0 via-zinc-300 to-zinc-500/0" />
        </span>
    );
};

const SplashButton = ({ children, className, ...rest }) => {
    return (
        <button
            className={twMerge(
                "rounded-md bg-gradient-to-br from-blue-400 to-blue-700 px-4 py-2 text-zinc-50 ring-2 ring-blue-500/50 ring-offset-2 ring-offset-zinc-950 transition-all hover:scale-[1.02] hover:ring-transparent active:scale-[0.98] active:ring-blue-500/70",
                className
            )}
            {...rest}
        >
            {children}
        </button>
    );
};

// DrawOutlineButton Component
const DrawOutlineButton = ({ children, ...rest }) => {
    return (
        <button
            {...rest}
            className="group relative px-4 py-2 font-medium text-slate-100 transition-colors duration-[400ms] hover:text-indigo-300"
        >
            <span>{children}</span>

            {/* TOP */}
            <span className="absolute left-0 top-0 h-[2px] w-0 bg-indigo-300 transition-all duration-100 group-hover:w-full" />

            {/* RIGHT */}
            <span className="absolute right-0 top-0 h-0 w-[2px] bg-indigo-300 transition-all delay-100 duration-100 group-hover:h-full" />

            {/* BOTTOM */}
            <span className="absolute bottom-0 right-0 h-[2px] w-0 bg-indigo-300 transition-all delay-200 duration-100 group-hover:w-full" />

            {/* LEFT */}
            <span className="absolute bottom-0 left-0 h-0 w-[2px] bg-indigo-300 transition-all delay-300 duration-100 group-hover:h-full" />
        </button>
    );
};

// Beams
const Beams = () => {
    const { width } = useWindowSize();
    const numColumns = width ? Math.floor(width / GRID_BOX_SIZE) : 0;

    const placements = [
        { top: 0, left: Math.floor(numColumns * 0.05) * GRID_BOX_SIZE, transition: { duration: 3.5, repeatDelay: 5, delay: 2 } },
        { top: GRID_BOX_SIZE * 12, left: Math.floor(numColumns * 0.15) * GRID_BOX_SIZE, transition: { duration: 3.5, repeatDelay: 10, delay: 4 } },
        { top: GRID_BOX_SIZE * 3, left: Math.floor(numColumns * 0.25) * GRID_BOX_SIZE },
        { top: GRID_BOX_SIZE * 9, left: Math.floor(numColumns * 0.75) * GRID_BOX_SIZE, transition: { duration: 2, repeatDelay: 7.5, delay: 3.5 } },
        { top: 0, left: Math.floor(numColumns * 0.7) * GRID_BOX_SIZE, transition: { duration: 3, repeatDelay: 2, delay: 1 } },
        { top: GRID_BOX_SIZE * 2, left: Math.floor(numColumns * 1) * GRID_BOX_SIZE - GRID_BOX_SIZE, transition: { duration: 5, repeatDelay: 5, delay: 5 } }
    ];

    return (
        <>
            {placements.map((p, i) => (
                <Beam key={i} top={p.top} left={p.left - BEAM_WIDTH_OFFSET} transition={p.transition || {}} />
            ))}
        </>
    );
};

const Beam = ({ top, left, transition = {} }) => {
    return (
        <motion.div
            initial={{ y: 0, opacity: 0 }}
            animate={{ opacity: [0, 1, 0], y: 32 * 8 }}
            transition={{ ease: "easeInOut", duration: 3, repeat: Infinity, repeatDelay: 1.5, ...transition }}
            style={{ top, left }}
            className="absolute z-10 h-[64px] w-[1px] bg-gradient-to-b from-blue-500/0 to-blue-500"
        />
    );
};

// Gradient Grid
const GradientGrid = () => {
    return (
        <motion.div
            initial={{ opacity: 0 }}
            animate={{ opacity: 1 }}
            transition={{ duration: 2.5, ease: "easeInOut" }}
            className="absolute inset-0 z-0"
        >
            <div
                style={{
                    backgroundImage: `url("data:image/svg+xml,%3csvg xmlns='http://www.w3.org/2000/svg' viewBox='0 0 32 32' width='32' height='32' fill='none' stroke-width='2' stroke='rgb(30 58 138 / 0.5)'%3e%3cpath d='M0 .5H31.5V32'/%3e%3c/svg%3e")`,
                }}
                className="absolute inset-0 z-0"
            />
            <div className="absolute inset-0 z-10 bg-gradient-to-b from-zinc-950/0 to-zinc-950" />
        </motion.div>
    );
};

// Utility Hooks
const useWindowSize = () => {
    const [windowSize, setWindowSize] = useState({ width: undefined, height: undefined });

    useEffect(() => {
        const handleResize = () =>
            setWindowSize({ width: window.innerWidth, height: window.innerHeight });

        window.addEventListener("resize", handleResize);
        handleResize();

        return () => {
            window.removeEventListener("resize", handleResize);
        };
    }, []);

    return windowSize;
};

const handleLinkClick = (e, targetId) => {
    e.preventDefault();
    const targetElement = document.getElementById(targetId);
    if (targetElement) {
        targetElement.scrollIntoView({ behavior: "smooth" });
    }
};

// Constants
const GRID_BOX_SIZE = 32;
const BEAM_WIDTH_OFFSET = 1;

export default DarkGridHero;

// src/lib/components/Hero.svelte
<script>
    import {onMount} from 'svelte';
    import Meteors from "$lib/components/ui/Meteors.svelte";

    onMount(() => {
        const begin = document.getElementById('to-section-2');
        if (begin) {
            begin.addEventListener('click', () => {
                setTimeout(() => history.replaceState(null, '', ' '), 10);
            });
        }

        const back = document.getElementById('to-section-1');
        if (back) {
            back.addEventListener('click', () => {
                setTimeout(() => history.replaceState(null, '', ' '), 10);
            });
        }
    });

    let journeySection;

    onMount(() => {
        journeySection = document.getElementById('part2');

        const button = document.getElementById('to-section-2');
        if (button && journeySection) {
            button.addEventListener('click', (e) => {
                e.preventDefault();

                const headerOffset = 90;
                const elementPosition = journeySection.getBoundingClientRect().top;
                const offsetPosition = elementPosition + window.pageYOffset - headerOffset;

                window.scrollTo({
                    top: offsetPosition,
                    behavior: 'smooth'
                });
            });
        }
    });
</script>

<section class="relative overflow-hidden z-10 pt-35 md:pt-40 xl:pt-45 mb-20 min-h-screen" id="home">
    <div class="max-w-7xl mx-auto">
        <div class="absolute -z-10 pointer-events-none inset-0 overflow-hidden -mx-28">
            <div class="absolute -z-1 -top-[128%] sm:-top-[107%] xl:-top-[73%] left-1/2 -translate-x-1/2 hero-circle-gradient w-full h-[1282px] rounded-full max-w-[1282px]"></div>
            <div class="absolute -z-1 -top-[112%] sm:-top-[93%] xl:-top-[62%] left-1/2 -translate-x-1/2 hero-circle-gradient w-full h-[1046px] rounded-full max-w-[1046px]"></div>
            <div class="absolute top-0 left-1/2 -translate-x-1/2 -u-z-100">
                <img alt="blur" class="max-w-none" src="./images/blur/blur-02.svg"/>
            </div>
            <div class="absolute top-0 left-1/2 -translate-x-1/2 -u-z-100">
                <img alt="blur" class="max-w-none" src="./images/blur/blur-01.svg"/>
            </div>
        </div>
    </div>

    <div class="flex flex-col items-center justify-center space-y-7 mt-[12vh] md:mt-[12vh]">
        <div class="w-auto text-center fade-in">
            <h1 class="text-6xl font-bold bg-gradient-to-r from-accent to-white bg-clip-text text-transparent">
                Jacob Jørgensen
            </h1>

            <div class="flex justify-center gap-4 mt-4">
                <a href="https://github.com/zelvios" rel="noopener noreferrer" target="_blank">
                    <button class="flex items-center gap-2 cursor-pointer text-white text-sm font-medium bg-gradient-to-r from-gray-800 to-black px-4 py-2 rounded-full border border-gray-600 hover:scale-105 duration-200 hover:text-accent hover:border-gray-800 hover:from-black hover:to-gray-900">
                        <svg height="18" viewBox="0 0 24 24" width="18" xmlns="http://www.w3.org/2000/svg">
                            <path d="M12 0c-6.626 0-12 5.373-12 12 0 5.302 3.438 9.8 8.207 11.387.599.111.793-.261.793-.577v-2.234c-3.338.726-4.033-1.416-4.033-1.416-.546-1.387-1.333-1.756-1.333-1.756-1.089-.745.083-.729.083-.729 1.205.084 1.839 1.237 1.839 1.237 1.07 1.834 2.807 1.304 3.492.997.107-.775.418-1.305.762-1.604-2.665-.305-5.467-1.334-5.467-5.931 0-1.311.469-2.381 1.236-3.221-.124-.303-.535-1.524.117-3.176 0 0 1.008-.322 3.301 1.23.957-.266 1.983-.399 3.003-.404 1.02.005 2.047.138 3.006.404 2.291-1.552 3.297-1.23 3.297-1.23.653 1.653.242 2.874.118 3.176.77.84 1.235 1.911 1.235 3.221 0 4.609-2.807 5.624-5.479 5.921.43.372.823 1.102.823 2.222v3.293c0 .319.192.694.801.576 4.765-1.589 8.199-6.086 8.199-11.386 0-6.627-5.373-12-12-12z"
                                  fill="#FFFFFF"/>
                        </svg>
                        Github
                    </button>
                </a>

                <a href="https://www.linkedin.com/in/jacob-j-in/" rel="noopener noreferrer" target="_blank">
                    <button class="flex items-center gap-2 cursor-pointer text-white text-sm font-medium bg-gradient-to-r from-gray-800 to-black px-4 py-2 rounded-full border border-gray-600 hover:scale-105 duration-200 hover:text-accent hover:border-gray-800 hover:from-black hover:to-gray-900">
                        <svg height="18" viewBox="0 0 24 24" width="18" xmlns="http://www.w3.org/2000/svg">
                            <path d="M4.98 3.5C4.98 4.88 3.87 6 2.5 6S0 4.88 0 3.5 1.12 1 2.5 1 4.98 2.12 4.98 3.5zM.5 24h4V7H.5v17zM8.5 7H12v2.5h.06c.49-.92 1.7-1.9 3.44-1.9 3.68 0 4.5 2.42 4.5 5.57V24h-4v-8.17c0-1.95-.03-4.47-2.72-4.47-2.73 0-3.15 2.13-3.15 4.33V24h-4V7z"
                                  fill="#FFFFFF"/>
                        </svg>
                        LinkedIn
                    </button>
                </a>
            </div>

            <div class="max-w-prose mx-auto mt-16">
                <p class="text-md text-text mt-3 text-center" style="line-height: 1.5;">
                    I’m a computer technician student specializing in programming, studying in Aalborg, Denmark.
                    I focus on building reliable software and continuously developing my technical skills.
                    You can check out my projects, contributions, and experiments in full-stack development on GitHub.
                </p>
            </div>
        </div>

        <Meteors/>
        <div class="relative group fade-in">
            <a id="to-section-2"
               class="relative inline-block p-px font-semibold leading-6 text-text bg-base shadow-lg cursor-pointer rounded-2xl shadow-accent transition-all duration-300 ease-in-out hover:scale-105 active:scale-95 hover:shadow-accent">
                <span class="absolute inset-0 rounded-2xl bg-gradient-to-r from-accent via-text to-surface1 p-[2px] opacity-0 transition-opacity duration-500 group-hover:opacity-100"></span>
                <span class="relative z-10 block px-6 py-3 rounded-2xl bg-base">
            <span class="relative z-10 flex items-center space-x-3">
                <span class="transition-all duration-500 group-hover:translate-x-1.5 group-hover:text-accent">Begin Journey</span>
                <svg class="w-7 h-7 transition-all duration-500 group-hover:translate-y-1.5 group-hover:text-accent rotate-90"
                     viewBox="0 0 24 24">
                    <path d="M16.172 11l-5.364-5.364 1.414-1.414L20 12l-7.778 7.778-1.414-1.414L16.172 13H4v-2z"
                          fill="currentColor"></path>
                </svg>
            </span>
        </span>
            </a>
        </div>
    </div>

    <div class="w-auto fade-in mt-20 mb-0 flex justify-center">
        <img alt="Tab Icon" class="mx-auto" src="/images/tab.svg"/>
    </div>
</section>

<style>
    .fade-in {
        animation: fadeIn 1s ease-out;
    }

    @keyframes fadeIn {
        0% {
            opacity: 0;
            transform: translateY(20px);
        }
        100% {
            opacity: 1;
            transform: translateY(0);
        }
    }
</style>
